[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
healthcheckPath = "/"
restartPolicyType = "always"